# domain: andi-254.github.io/simple-screen-recorder/
title: Simple screen recorder
author: Adrian Mache
email: andi146@photonemail.com
description: > # this means to ignore newlines until "baseurl:"
  personal project dev log

# social links
twitter_username: Adrian # DO NOT include the @ character, or else the build will fail!
github_username:  Andi-146 # DO NOT include the @ character, or else the build will fail!
discord_username : andi-146

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman 

url: https://andi-254.github.io/simple-screen-recorder/  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /simple-screen-recorder/_config.yml      # place folder name if the site is served in a subfolder
